# Generated by Django 3.0 on 2022-10-10 23:46

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0001_initial'),
    ]
                # ('stockNum', models.IntegerField(default=0)),
                # ('stockOnOrder', models.IntegerField(default=0)),

    operations = [
        migrations.AddField(
            model_name='product',
            name='stockNum',
            field=models.IntegerField(default=0),
        ),
    ]
