# Generated by Django 3.0 on 2022-10-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0002_auto_20221011_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stockNum',
            new_name='pendingStock',
        ),
        migrations.AddField(
            model_name='product',
            name='stockAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
