# Generated by Django 3.0 on 2022-10-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0003_auto_20221011_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
    ]
