# Generated by Django 3.0 on 2022-09-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0002_auto_20220912_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currentStock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('supplierProductID', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('currentStock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end_application.Product')),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end_application.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stockID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=15)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end_application.Customer')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end_application.Product')),
            ],
        ),
    ]
