# Generated by Django 3.0 on 2022-09-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0002_auto_20220911_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
