# Generated by Django 3.0 on 2022-08-22 09:19

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0002_supplier_supplyorder_supplyorderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStatus',
            fields=[
                ('batchStatusID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('shippingAddress', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderContents',
            fields=[
                ('customerOrderContentsID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end_application.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('customerOrderID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end_application.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchID', models.AutoField(primary_key=True, serialize=False)),
                ('dateReceived', models.DateTimeField()),
                ('expiryDate', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end_application.Product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end_application.BatchStatus')),
            ],
        ),
    ]
