# Generated by Django 3.0 on 2022-10-10 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back_end_application', '0002_supplier_supplyorder_supplyorderstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stockCount',
            new_name='stockNum',
        )
        # migrations.AlterField(
        #     model_name='supplier',
        #     name='phone',
        #     field=models.IntegerField(default=0),
        # ),
        # migrations.AlterField(
        #     model_name='supplier',
        #     name='supplierID',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='supplyorder',
        #     name='supplyOrderID',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='supplyorderstatus',
        #     name='updateID',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
    ]
