# Generated by Django 3.0 on 2022-09-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0005_auto_20220911_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='shippingAddress',
            new_name='shipping_address',
        ),
    ]
