# Generated by Django 3.0 on 2022-09-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0005_auto_20220920_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerordercontents',
            name='supplierID',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='back_end_application.Supplier'),
            preserve_default=False,
        ),
    ]
