# Generated by Django 3.0 on 2022-09-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0007_auto_20220920_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderStatus',
            fields=[
                ('updateID', models.AutoField(primary_key=True, serialize=False)),
                ('updateType', models.CharField(choices=[('DLY', 'Delayed'), ('COM', 'Completed'), ('SNT', 'Sent'), ('CNC', 'Cancelled'), ('OTH', 'Other')], max_length=512)),
            ],
        ),
    ]
