# Generated by Django 3.0 on 2022-09-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0007_auto_20220910_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerID',
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
